EP3/config/routes.rb
Rails.application.routes.draw do
  get 'adm_page/index'

  devise_for :admins
  resources :borrows
  resources :games
  resources :albums
  resources :books
  get 'contact/index'

  get 'services/index'

  get 'about/index'

  devise_for :users
  get 'home_user/index'
  get 'inicio/index'
  get 'home_user/index'
  root 'inicio#index'

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :adm_page

end

EP3/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

EP3/app/models/album.rb
class Album < ActiveRecord::Base
	validates_presence_of :band, :description
	validates :name, presence: true
end

EP3/app/models/book.rb
class Book < ActiveRecord::Base
	validates_presence_of :title, :author, :description
end
	

EP3/app/models/borrow.rb
class Borrow < ActiveRecord::Base
	validates_presence_of :idtitle, :renter
	validates :initialdate, presence: true
	validates :finaldate, presence: true
	validates :itemtype, presence: true
end

EP3/app/models/game.rb
class Game < ActiveRecord::Base
	validates_presence_of :title, :developer, :description
end

EP3/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :image, presence: true
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

EP3/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

EP3/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Livro cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Livro atualizado!' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Livro destruido!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:iduser, :title, :author, :description, :borrow)
    end
end

EP3/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Jogo cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Jogo atualizado.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Jogo deletado!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:iduser, :title, :developer, :description, :borrow)
    end
end

EP3/app/controllers/home_user_controller.rb
class HomeUserController < ApplicationController
	before_action :authenticate_user!
  def index
    @books = Book.all
    @games = Game.all
    @albums = Album.all
    @borrows = Borrow.all
  end
end

EP3/app/helpers/about_helper.rb
module AboutHelper
end

EP3/app/helpers/adm_page_helper.rb
module AdmPageHelper
end

EP3/app/helpers/albums_helper.rb
module AlbumsHelper
end

EP3/app/helpers/application_helper.rb
module ApplicationHelper
end

EP3/app/helpers/books_helper.rb
module BooksHelper
end

EP3/app/helpers/borrows_helper.rb
module BorrowsHelper
end

EP3/app/helpers/contact_helper.rb
module ContactHelper
end

EP3/app/helpers/games_helper.rb
module GamesHelper
end

EP3/app/helpers/home_user_helper.rb
module HomeUserHelper
end

EP3/app/helpers/inicio_helper.rb
module InicioHelper
end

EP3/app/helpers/services_helper.rb
module ServicesHelper
end

EP3/app/helpers/users_helper.rb
module UsersHelper
end

EP3/app/views/home_user/index.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bem Vindo(a), <%= current_user.name%>!</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                      <div class="btn-group">
                        <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Novo <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                          <li>
                              <%= link_to "Livro", new_book_path%>
                          </li>      
                          <li>
                              <%= link_to "Álbum", new_album_path %>
                          </li>    
                          <li>
                              <%= link_to "Jogo", new_game_path %>
                          </li> 
                          <li role="separator" class="divider"></li>
                          <li>
                              <%= link_to "Empréstimo", new_borrow_path %>
                          </li> 
                        </ul>
                      </div>
                    </li>                                                
                    <li>
          				<%= link_to "Editar Perfil", edit_user_registration_path %>
                    </li>    
                    <li>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </li>        
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<h1><center><b>Acervo de <%=current_user.name%></b></center></h1>
<center><%= image_tag current_user.image.url(:medium) %></center>
<p><center><b>Seu e-mail cadastrado é: <%=current_user.email%>.</b></center></p>

  <!-- recebendo o valor de current_user.id e transformando ele para string. Isso permitirá que ele possa ser comparado com o iduser -->
    <% validation = current_user.id.to_s %>

<!-- São laços que lêm todo o banco de cada item e printam eles numa tabela. Os "if" comparam o iduser com o id do usuario e só permitem printar os que forem iguais -->

<h2> Livros cadastrados em seu acervo: </h2>
<%if (@books.size > 0)%>
<table border 3 class="tableUser">
  <thead>
    <tr>
      <th bgcolor="WHITE">Título</th>
      <th bgcolor="WHITE">Autor</th>
      <th bgcolor="WHITE">Descrição</th>
      <th bgcolor="WHITE">Empréstimo</th>
      <th colspan="3", bgcolor="WHITE">Gerenciamento </th>
    </tr>
  </thead>

  <tbody>
  <!-- recebendo o valor de current_user.id e transformando ele para string. Isso permitirá que ele possa ser comparado com o iduser -->
    <% validation = current_user.id.to_s %>
    <% @books.each do |book| %>
        <%if (book.iduser == validation)%>
      <tr>
        <td WIDTH=100, bgcolor="WHITE"><%= book.title %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= book.author %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= book.description %></td>
            <%if (book.borrow == false) %>
        <td WIDTH=100, bgcolor="GREEN"></td>
            <%else%>
        <td WIDTH=100, bgcolor="RED"></td>
        <%end%>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Mostrar', book, :class => "btn btn-primary btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Atualizar', edit_book_path(book), :class => "btn btn-success btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Deletar', book, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => "btn btn-danger btn-xs active", :role => "button" %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Nenhum livro cadastrado</p>
<% end %>
<br>
<a href="<%= new_book_path %>" class="btn btn-primary btn-sm active" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo Livro</a>
<br>

<h2>Álbuns cadastrados em seu acervo:</h2>
<%if (@albums.size > 0)%>
<table border 3 class="tableUser">
  <thead>
    <tr>
      <th WIDTH=100, bgcolor="WHITE">Banda</th>
      <th WIDTH=100, bgcolor="WHITE">Nome</th>      
      <th WIDTH=100, bgcolor="WHITE">Descrição</th>
      <th WIDTH=100, bgcolor="WHITE">Empréstimo</th>
      <th colspan="3" WIDTH=100, bgcolor="WHITE">Gerenciamento</th>
    </tr>
  </thead>

  <tbody>
    <% validation = current_user.id.to_s %>
    <% @albums.each do |album| %>
      <%if (album.iduser == validation)%>
      <tr>
        <td WIDTH=100, bgcolor="WHITE"><%= album.band %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= album.name %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= album.description %></td>
            <%if (album.borrow == false) %>
        <td WIDTH=100, bgcolor="GREEN"></td>
            <%else%>
        <td WIDTH=100, bgcolor="RED"></td>
        <%end%>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Mostrar', album, :class => "btn btn-primary btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Atualizar', edit_album_path(album), :class => "btn btn-success btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Deletar', album, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => "btn btn-danger btn-xs active", :role => "button" %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Nenhum álbum cadastrado</p>
<% end %>
<br>
<a href="<%= new_album_path %>" class="btn btn-primary btn-sm active" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo Álbum</a>
<br>

<h2>Jogos cadastrados em seu acervo:</h2>

<%if (@games.size > 0)%>
<table border 3 class="tableUser">
  <thead>
    <tr>
      <th bgcolor="WHITE">Título</th>
      <th bgcolor="WHITE">Desenvolvedora</th>
      <th bgcolor="WHITE">Descrição</th>
      <th bgcolor="WHITE">Empréstimo</th>
      <th colspan="3", bgcolor="WHITE"> Gerenciamento</th>
    </tr>
  </thead>

  <tbody>
    <% validation = current_user.id.to_s %>
    <% @games.each do |game| %>
      <%if (game.iduser == validation)%>
      <tr>
        <td WIDTH=100, bgcolor="WHITE"><%= game.title %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= game.developer %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= game.description %></td>
            <%if (game.borrow == false) %>
        <td WIDTH=100, bgcolor="GREEN"></td>
            <%else%>
        <td WIDTH=100, bgcolor="RED"></td>
        <%end%>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Mostrar', game, :class => "btn btn-primary btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Atualizar', edit_game_path(game), :class => "btn btn-success btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Deletar', game, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => "btn btn-danger btn-xs active", :role => "button" %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Nenhum jogo cadastrado</p>
<% end %>
<br>
<a href="<%= new_game_path %>" class="btn btn-primary btn-sm active" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo Jogo</a>
<br>

<h2>Empréstimos do seu acervo:</h2>

<%if (@borrows.size > 0)%>
<table border 3 class="tableUser">
  <thead>
    <tr>
      <th WIDTH=100, bgcolor="WHITE">Titulo Emprestado</th>
      <th WIDTH=100, bgcolor="WHITE">Para</th>
      <th WIDTH=100, bgcolor="WHITE">Tipo do Item</th>
      <th WIDTH=100, bgcolor="WHITE">Data Inicial do Empréstimo</th>
      <th WIDTH=100, bgcolor="WHITE">Data Final do Empréstimo</th>
      <th colspan="3" WIDTH=100, bgcolor="WHITE">Gerenciamento</th>
    </tr>
  </thead>

  <tbody>
    <% validation = current_user.id.to_s %>
    <% @borrows.each do |borrow| %>
      <%if (borrow.iduser == validation)%>      
      <tr> 
        <td WIDTH=100, bgcolor="WHITE"><%= borrow.idtitle %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= borrow.renter %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= borrow.itemtype %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= borrow.initialdate %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= borrow.finaldate %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Mostrar', borrow, :class => "btn btn-primary btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Atualizar', edit_borrow_path(borrow), :class => "btn btn-success btn-xs active", :role => "button" %></td>
        <td WIDTH=100, bgcolor="WHITE"><%= link_to 'Deletar', borrow, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => "btn btn-danger btn-xs active", :role => "button" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Nenhum empréstimo cadastrado</p>
<% end %>
<br>
<a href="<%= new_borrow_path %>" class="btn btn-primary btn-sm active" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo Empréstimo</a>
<br>
<br>